baseURL = "/"
title = "Volt.cx Documentation"
languageCode = "en-us"
DefaultContentLanguage = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
disableHomeIcon = true
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
github_repo = "https://github.com/volt-cx/docs/"
github_project_repo = "https://github.com/volt.cx/"
offlineSearch = true

[outputs]
home = ["HTML","RSS","JSON"]
page = ["HTML","JSON"]
section = ["HTML","JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Volt.cx repo</label>"
identifier = "ds"
url = "https://github.com/vjeantet/hugo-theme-docdock"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "https://github.com/vjeantet/hugo-theme-docdock/archive/master.zip"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Hugo Documentation</label>"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "/credits"
weight = 30
